---
- hosts: all
  become_user: "{{ user }}"
  become: true
  tasks:
    - name: Set up app directory
      file: name=~/app state=directory

    - name: Unarchive ghost
      unarchive: src=../files/ghost.zip dest=~/app creates=~/app/index.js

    - name: Copy ghost config
      template: src=../templates/config.js dest=~/app/config.js

    - name: Install Attila theme
      unarchive: src=../files/attila-theme.zip dest=~/app/content/themes

    - name: Install dependencies
      npm: path=~/app production=yes

    - name: Tighten up permissions
      file: name='~' mode='u+rw,o-rwx' recurse=yes
